spring:
# datasource:
#   url: jdbc:postgresql:envers
#   url: jdbc:mysql://localhost/envers?useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
